apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: eshoponweb
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: eshoponweb
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: eshoponweb
spec:
  source:
    git:
      url: https://github.com/jrobinsonvm/eShopOnWeb
      ref:
        branch: main
